main:
  clusterGroupName: datacenter

global:
  pattern: industrial-edge

  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  imageregistry:
    account: acossett
    hostname: quay.io
    type: quay

  git:
    hostname: github.com
    account: amelie1979
    #username: PLAINTEXT
    email: acossett@redhat.com
    dev_revision: main

  s3:
    bucket:
      name: BUCKETNAME
      region: us-east-2
      message:
        aggregation:
          count: 50
      custom:
        endpoint:
          enabled: false
